// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTZMEgkxwd2jnV3BVaRggya4Mn4t3ljUU',
    appId: '1:825801371164:web:33ddfca4364b5e0da8b9d9',
    messagingSenderId: '825801371164',
    projectId: 'qltv2602',
    authDomain: 'qltv2602.firebaseapp.com',
    storageBucket: 'qltv2602.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqU4q5QphZle_AqN-h_X4ei1O6MLdCxps',
    appId: '1:825801371164:android:e3ac85f105386004a8b9d9',
    messagingSenderId: '825801371164',
    projectId: 'qltv2602',
    storageBucket: 'qltv2602.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuxMwG2Tsvsm9cozREUlcz-Q63tXbZrkk',
    appId: '1:825801371164:ios:5bd6b4e25022d1f4a8b9d9',
    messagingSenderId: '825801371164',
    projectId: 'qltv2602',
    storageBucket: 'qltv2602.firebasestorage.app',
    iosBundleId: 'com.example.elmouaddibeExamen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuxMwG2Tsvsm9cozREUlcz-Q63tXbZrkk',
    appId: '1:825801371164:ios:5bd6b4e25022d1f4a8b9d9',
    messagingSenderId: '825801371164',
    projectId: 'qltv2602',
    storageBucket: 'qltv2602.firebasestorage.app',
    iosBundleId: 'com.example.elmouaddibeExamen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTZMEgkxwd2jnV3BVaRggya4Mn4t3ljUU',
    appId: '1:825801371164:web:3ccbe6d29e7b98fca8b9d9',
    messagingSenderId: '825801371164',
    projectId: 'qltv2602',
    authDomain: 'qltv2602.firebaseapp.com',
    storageBucket: 'qltv2602.firebasestorage.app',
  );
}
